version: "3.6"
services:
  node:
    build: .
    volumes:
      - .:/app
  postgres:
    image: postgres
    restart: unless-stopped
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
