version: "3.6"
services:
  node:
    container_name: starter_node
    command: npm run start:debug
    environment:
      NPM_INSTALL: ENABLE
      TYPEORM_MIGRATION: ENABLE
    ports:
      - 3000:3000
      - 5858:5858
  postgres:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="starter-api","starter-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - starter_api_data:/data/postgres
    ports:
      - 5432:5432
  es01:
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200   
volumes:
  starter_api_data: {}
  data01: {}